#version: '3.8'
services:
  springboot-app:
    container_name: springboot-app
    image: hyewonbae/nolmung
    ports:
      - "443:8080"
    volumes:
      - /home/ec2-user/logs/info:/app/logs
    environment:
      SPRING_LOGGING_FILE_PATH: /app/logs/application.log
    #    environment:
    #      SPRING_PROFILES_ACTIVE: prod
    restart: always
    networks:
      - t4y

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/config:/etc/prometheus
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    command:
      - '--storage.tsdb.path=/prometheus'
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always
    networks:
      - t4y

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SECURITY_ADMIN_PASSWORD=nolmung
    restart: always
    networks:
      - t4y

  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    ports:
      - "3100:3100"
    restart: always
    networks:
      - t4y

  promtail:
    image: grafana/promtail:2.9.2
    container_name: promtail
    volumes:
      - ./logs:/logs
      - ./promtail-config.yml:/etc/promtail/config.yml
    command:
      - -config.file=/etc/promtail/config.yml
      - -config.expand-env=true
    restart: always
    networks:
      - t4y

networks:
  t4y:
    driver: bridge

volumes:
  prometheus-data: