version: '3.8'

services:
  springboot-app:
    container_name: thirsty_robinson
    image: hyewonbae/nolmung
    ports:
      - "443:8080"
#    environment:
#      SPRING_PROFILES_ACTIVE: prod
    restart: always
    networks:
      - t4y

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/config:/etc/prometheus
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    command:
      - '--storage.tsdb.path=/prometheus'
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always
    networks:
      - t4y

  grafana:
    image: grafana/grafana:7.5.2
    container_name: grafana
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "nolmung"
    depends_on:
      - prometheus
      - loki
    restart: always
    networks:
      - t4y

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    restart: always
    networks:
      - t4y

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./logs/backend:/logs
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    restart: always
    networks:
      - t4y

networks:
  t4y:
    driver: bridge

volumes:
  grafana-data:
  prometheus-data:
  loki-data: