version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: docker_redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  spring-app:
    container_name: thirsty_robinson
    image: hyewonbae/nolmung:dev
    ports:
      - "443:8080"
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
