global:
  scrape_interval: 1m
  scrape_timeout: 15s

scrape_configs:
  - job_name: "prometheus"
    scheme: https
    static_configs:
      - targets: ["api.nolmung.org:9090"]

  - job_name: "spring-actuator"
    metrics_path: "/actuator/prometheus"
    scheme: https
    static_configs:
      - targets: ["api.nolmung.org"]
