positions:
  filename: /tmp/positions.yaml # 동기화 작업을 이루기 위해 promtail이 읽은 마지막 로그 정보를 저장하는 곳

clients:
  - url: https://api.nolmung.org:3100/loki/api/v1/push # push할 Loki의 주소

scrape_configs:
  - job_name: info
    scheme: https
    static_configs:
      - targets:
          - api.nolmung.org
        labels:
          job: info_logs
          __path__: ./logs/info/*.log # info 폴더 내에 log 파일들 모두 수집

  - job_name: warn
    scheme: https
    static_configs:
      - targets:
          - api.nolmung.org
        labels:
          job: warn_logs
          __path__: ./logs/warn/*.log # warn 폴더 내에 log 파일들 모두 수집

  - job_name: error
    scheme: https
    static_configs:
      - targets:
          - api.nolmung.org
        labels:
          job: error_logs
          __path__: ./logs/error/*.log # error 폴더 내에 log 파일들 모두 수집