server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml # 동기화 작업을 이루기 위해 promtail이 읽은 마지막 로그 정보를 저장하는 곳

clients:
  - url: http://15.165.130.30:3100/loki/api/v1/push # push할 Loki의 주소

scrape_configs:
  - job_name: logging
    static_configs:
      - targets:
          - localhost
        labels:
          job: logging
          __path__: /logs/*.log