spring:
  datasource:
    url: jdbc:mysql://nolmung-db.cvui0gm6ga2b.ap-northeast-2.rds.amazonaws.com:3306/nolmung
    username: nolmung
    password: nolmung123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show-sql: true
        default_batch_fetch_size: 100

    open-in-view: false